# Pre-commit hook, designed to run some chores before every commit.

default_language_version:
  python: python3.9.2

default_stages: [ commit, push ]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: commit-chores
        name: commit-chores
        entry: bash commit-chores.sh
        language: system
